#include <iostream>

//389. Find the Difference
//You are given two strings s and t.String t is generated by random shuffling string s and then add one more letter at a random position.

char findTheDifference(std::string& s,std::string& t){
    if(s.size() == 0)
        return t[0];
    std::sort(s.begin(),s.end());
    std::sort(t.begin(),t.end());
    const size_t size = s.size();
    for(int i = 0;i<size;i++){
        if(s[i]!=t[i])
            return t[i];
    }
    return t[t.size() - 1];
}

int main(int argc, const char * argv[]) {
    std::string s = "ae";
    std::string t = "aea";
    std::cout<<findTheDifference(s, t)<<std::endl;
}
